### ISSUE TITLE
应用程序屡次崩溃

### ISSUE THREAD

**Issue by ChengzhiLiu** [HMBSbige/ShadowsocksR-Android#20]
--------- beginning of crash
11-11 14:30:03.609 2839 2839 E AndroidRuntime: FATAL EXCEPTION: main
11-11 14:30:03.609 2839 2839 E AndroidRuntime: Process: com.bige0.shadowsocksr, PID: 2839
11-11 14:30:03.609 2839 2839 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.bige0.shadowsocksr.ShadowsocksRunnerService@bec6432 with null: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter intent
11-11 14:30:03.609 2839 2839 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3922)
11-11 14:30:03.609 2839 2839 E AndroidRuntime: 	at android.app.ActivityThread.access$1700(ActivityThread.java:240)
11-11 14:30:03.609 2839 2839 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1828)
11-11 14:30:03.609 2839 2839 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-11 14:30:03.609 2839 2839 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
11-11 14:30:03.609 2839 2839 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7094)
11-11 14:30:03.609 2839 2839 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-11 14:30:03.609 2839 2839 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
11-11 14:30:03.609 2839 2839 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
11-11 14:30:03.609 2839 2839 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter intent
11-11 14:30:03.609 2839 2839 E AndroidRuntime: 	at com.bige0.shadowsocksr.ShadowsocksRunnerService.onStartCommand(Unknown Source:2)
11-11 14:30:03.609 2839 2839 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3903)
11-11 14:30:03.609 2839 2839 E AndroidRuntime: 	... 8 more
11-11 14:30:09.504 3106 3106 E AndroidRuntime: FATAL EXCEPTION: main
11-11 14:30:09.504 3106 3106 E AndroidRuntime: Process: com.bige0.shadowsocksr, PID: 3106
11-11 14:30:09.504 3106 3106 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.bige0.shadowsocksr.ShadowsocksRunnerService@bec6432 with null: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter intent
11-11 14:30:09.504 3106 3106 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3922)
11-11 14:30:09.504 3106 3106 E AndroidRuntime: 	at android.app.ActivityThread.access$1700(ActivityThread.java:240)
11-11 14:30:09.504 3106 3106 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1828)
11-11 14:30:09.504 3106 3106 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-11 14:30:09.504 3106 3106 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
11-11 14:30:09.504 3106 3106 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7094)
11-11 14:30:09.504 3106 3106 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-11 14:30:09.504 3106 3106 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
11-11 14:30:09.504 3106 3106 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
11-11 14:30:09.504 3106 3106 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter intent
11-11 14:30:09.504 3106 3106 E AndroidRuntime: 	at com.bige0.shadowsocksr.ShadowsocksRunnerService.onStartCommand(Unknown Source:2)
11-11 14:30:09.504 3106 3106 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3903)
11-11 14:30:09.504 3106 3106 E AndroidRuntime: 	... 8 more

**Comment by ChengzhiLiu** [comment]
![Screenshot_20191111-143804_Smart Manager](https://user-images.githubusercontent.com/41582329/68566596-c4fe7180-0491-11ea-9a3c-d7fc845db09a.jpg)

**Comment by ChengzhiLiu** [comment]
软件版本：V3.6.0
系统版本：Android 9.0 三星 One UI
复现频率：每天
具体表现：无预兆地卡死或黑屏，弹出应用程序屡次停止运行窗口，但随后软件自动恢复正常运行
